import { readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { canonicalJson } from '@nawara/service-kit';
import type { Catalog, CatalogTemplate, CatalogVersion } from './catalog.js';

/**
 * Publishing (SDD §6.1): the catalog becomes INSERT statements in a numbered migration `NNNN_publish_templates_*.sql`, one statement
 * per line, generated and never hand-edited. The kit migration runner checksums the file (tamper-evident), the rows are immutable
 * (triggers), and a unit test proves the committed migrations contain exactly the statements the catalog generates: no version edited
 * after publication, none missing, none invented.
 */
export const PUBLISH_MIGRATION = /^\d{4}_publish_templates_[a-z0-9_]+\.sql$/;

/** A PostgreSQL escape-string literal on ONE line (newlines, tabs, quotes and backslashes escaped). */
function lit(v: string | number | null): string {
  if (v === null) return 'NULL';
  if (typeof v === 'number') return String(v);
  const escaped = v.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n').replace(/\r/g, '\\r').replace(/\t/g, '\\t');
  return `E'${escaped}'`;
}

export function templateStatement(t: CatalogTemplate): string {
  return `INSERT INTO notification_template (id, key, category, "ownerScope", description) VALUES (${lit(t.id)}, ${lit(t.key)}, ${lit(t.category)}, 'platform', ${lit(t.description)});`;
}

export function versionStatement(v: CatalogVersion): string {
  return (
    'INSERT INTO notification_template_version (id, "templateId", channel, locale, version, variables, subject, "bodyText", "bodyHtml", "smsMaxSegments", checksum) ' +
    `VALUES (${lit(v.id)}, ${lit(v.templateId)}, ${lit(v.channel)}, ${lit(v.locale)}, ${v.version}, ${lit(canonicalJson(v.variables))}::jsonb, ` +
    `${lit(v.subject)}, ${lit(v.bodyText)}, ${lit(v.bodyHtml)}, ${lit(v.smsMaxSegments)}, ${lit(v.checksum)});`
  );
}

/** Every statement the catalog generates, templates first (a version references its template). */
export function catalogStatements(catalog: Catalog): string[] {
  return [...catalog.templates.map(templateStatement), ...catalog.versions.map(versionStatement)];
}

/** The INSERT statements already committed in the publishing migrations of `migrationsDir`. */
export function publishedStatements(migrationsDir: string): string[] {
  return readdirSync(migrationsDir)
    .filter((f) => PUBLISH_MIGRATION.test(f))
    .sort()
    .flatMap((f) => readFileSync(join(migrationsDir, f), 'utf8').split('\n').filter((l) => l.startsWith('INSERT INTO ')));
}

/** The content of the next publishing migration: every statement the catalog generates that no committed migration contains yet. */
export function nextPublishMigration(catalog: Catalog, migrationsDir: string): string | undefined {
  const published = new Set(publishedStatements(migrationsDir));
  const pending = catalogStatements(catalog).filter((s) => !published.has(s));
  if (pending.length === 0) return undefined;
  return [
    '-- Generated by `npm run templates:migration` from apps/notification-service/templates (SDD §6.1). Never edit by hand: a template',
    '-- change is a new version file and a new generated migration. The rows are immutable once inserted (triggers in 0001).',
    ...pending,
    '',
  ].join('\n');
}
