import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

/** OpenAPI documentation types ONLY; validation is `domain/organization-input.ts` (see `company.dto.ts`). */
export class CreateOrganizationDto {
  @ApiProperty({ format: 'uuid', description: 'The platform this organization belongs to. It must exist in this service. Immutable after creation.' })
  platformId!: string;
  @ApiProperty({ minLength: 1, maxLength: 200 })
  name!: string;
  @ApiPropertyOptional({ maxLength: 64, nullable: true })
  taxCode?: string | null;
  @ApiPropertyOptional({ maxLength: 500, nullable: true })
  address?: string | null;
  @ApiPropertyOptional({ maxLength: 32, nullable: true })
  phone?: string | null;
  @ApiPropertyOptional({ maxLength: 64, nullable: true, description: 'Generic and opaque: this service never validates or interprets it.' })
  type?: string | null;
}

export class UpdateOrganizationDto {
  @ApiPropertyOptional({ minLength: 1, maxLength: 200 })
  name?: string;
  @ApiPropertyOptional({ maxLength: 64, nullable: true, description: 'null clears the value.' })
  taxCode?: string | null;
  @ApiPropertyOptional({ maxLength: 500, nullable: true, description: 'null clears the value.' })
  address?: string | null;
  @ApiPropertyOptional({ maxLength: 32, nullable: true, description: 'null clears the value.' })
  phone?: string | null;
  @ApiPropertyOptional({ maxLength: 64, nullable: true, description: 'null clears the value.' })
  type?: string | null;
}

export class OrganizationDto {
  @ApiProperty({ format: 'uuid', description: 'Opaque identifier, generated by this service. Immutable.' })
  id!: string;
  @ApiProperty({ format: 'uuid' })
  platformId!: string;
  @ApiProperty()
  name!: string;
  @ApiProperty({ nullable: true, type: String })
  taxCode!: string | null;
  @ApiProperty({ nullable: true, type: String })
  address!: string | null;
  @ApiProperty({ nullable: true, type: String })
  phone!: string | null;
  @ApiProperty({ nullable: true, type: String })
  type!: string | null;
  @ApiProperty({ format: 'date-time' })
  createdAt!: string;
  @ApiProperty({ format: 'date-time' })
  updatedAt!: string;
}

export class OrganizationPageDto {
  @ApiProperty({ type: [OrganizationDto] })
  items!: OrganizationDto[];
  @ApiProperty({ nullable: true, type: String })
  nextCursor!: string | null;
}
