import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

/** OpenAPI documentation types ONLY; validation is `domain/platform-input.ts` (see `company.dto.ts`). */
export class CreatePlatformDto {
  @ApiProperty({ format: 'uuid', description: 'The company this platform belongs to. It must exist in this service. Immutable after creation.' })
  companyId!: string;
  @ApiProperty({ minLength: 1, maxLength: 200 })
  name!: string;
}

export class UpdatePlatformDto {
  @ApiPropertyOptional({ description: 'The new name. `companyId` cannot be changed. At least one field is required.', minLength: 1, maxLength: 200 })
  name?: string;
}

export class PlatformDto {
  @ApiProperty({ format: 'uuid', description: 'Opaque identifier, generated by this service. Immutable.' })
  id!: string;
  @ApiProperty({ format: 'uuid' })
  companyId!: string;
  @ApiProperty()
  name!: string;
  @ApiProperty({ nullable: true, type: String, pattern: '^[a-z][a-z0-9-]{1,39}$', description: 'Optional short public slug, unique when present. Returned as auth-service returns it; it cannot be set through this API.' })
  key!: string | null;
  @ApiProperty({ format: 'date-time' })
  createdAt!: string;
  @ApiProperty({ format: 'date-time' })
  updatedAt!: string;
}

export class PlatformPageDto {
  @ApiProperty({ type: [PlatformDto] })
  items!: PlatformDto[];
  @ApiProperty({ nullable: true, type: String })
  nextCursor!: string | null;
}
