import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

/**
 * OpenAPI documentation types ONLY. Request validation is `domain/company-input.ts` (the handlers take `unknown`): the test runner
 * does not emit decorator metadata, so a class-validator DTO would validate in production and silently not in tests.
 */
export class CreateCompanyDto {
  @ApiProperty({ description: 'The company name.', minLength: 1, maxLength: 200 })
  name!: string;
}

export class UpdateCompanyDto {
  @ApiPropertyOptional({ description: 'The new name. At least one field is required.', minLength: 1, maxLength: 200 })
  name?: string;
}

export class CompanyDto {
  @ApiProperty({ format: 'uuid', description: 'Opaque identifier, generated by this service. Immutable.' })
  id!: string;
  @ApiProperty()
  name!: string;
  @ApiProperty({ format: 'date-time' })
  createdAt!: string;
  @ApiProperty({ format: 'date-time' })
  updatedAt!: string;
}

export class CompanyPageDto {
  @ApiProperty({ type: [CompanyDto] })
  items!: CompanyDto[];
  @ApiProperty({ nullable: true, type: String, description: 'Opaque cursor for the next page; null when there is none.' })
  nextCursor!: string | null;
}
